name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Website
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: aimake-landing
          directory: website
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
